import type { ObjectCategory } from '../../core/types';

/** COCO label → HUD category + Japanese display name. */
export const COCO_MAP: Record<string, { category: ObjectCategory; ja: string; sub: string }> = {
  person: { category: 'person', ja: '人物', sub: '人物' },
  bicycle: { category: 'vehicle', ja: '自転車', sub: '車両' },
  car: { category: 'vehicle', ja: '乗用車', sub: '車両' },
  motorcycle: { category: 'vehicle', ja: 'バイク', sub: '車両' },
  bus: { category: 'vehicle', ja: 'バス', sub: '車両' },
  train: { category: 'train', ja: '電車', sub: '鉄道' },
  truck: { category: 'vehicle', ja: 'トラック', sub: '車両' },
  boat: { category: 'boat', ja: '船', sub: '船舶' },
  'traffic light': { category: 'road', ja: '信号機', sub: '道路' },
  'fire hydrant': { category: 'road', ja: '消火栓', sub: '道路' },
  'stop sign': { category: 'sign', ja: '一時停止標識', sub: '標識' },
  'parking meter': { category: 'road', ja: 'パーキングメーター', sub: '道路' },
  bench: { category: 'other', ja: 'ベンチ', sub: '設備' },
  bird: { category: 'animal', ja: '鳥', sub: '動物' },
  cat: { category: 'animal', ja: '猫', sub: '動物' },
  dog: { category: 'animal', ja: '犬', sub: '動物' },
  horse: { category: 'animal', ja: '馬', sub: '動物' },
  backpack: { category: 'product', ja: 'バックパック', sub: '商品' },
  umbrella: { category: 'product', ja: '傘', sub: '商品' },
  handbag: { category: 'product', ja: 'ハンドバッグ', sub: '商品' },
  bottle: { category: 'product', ja: 'ボトル', sub: '商品' },
  'wine glass': { category: 'product', ja: 'ワイングラス', sub: '食器' },
  cup: { category: 'food', ja: 'カップ', sub: '飲み物' },
  banana: { category: 'food', ja: 'バナナ', sub: '食べ物' },
  apple: { category: 'food', ja: 'りんご', sub: '食べ物' },
  sandwich: { category: 'food', ja: 'サンドイッチ', sub: '食べ物' },
  orange: { category: 'food', ja: 'オレンジ', sub: '食べ物' },
  pizza: { category: 'food', ja: 'ピザ', sub: '食べ物' },
  donut: { category: 'food', ja: 'ドーナツ', sub: '食べ物' },
  cake: { category: 'food', ja: 'ケーキ', sub: '食べ物' },
  chair: { category: 'other', ja: '椅子', sub: '家具' },
  couch: { category: 'other', ja: 'ソファ', sub: '家具' },
  'potted plant': { category: 'plant', ja: '観葉植物', sub: '植物' },
  bed: { category: 'other', ja: 'ベッド', sub: '家具' },
  'dining table': { category: 'other', ja: 'テーブル', sub: '家具' },
  tv: { category: 'appliance', ja: 'テレビ', sub: '家電' },
  laptop: { category: 'computer', ja: 'ノートPC', sub: 'PC' },
  mouse: { category: 'computer', ja: 'マウス', sub: 'PC周辺機器' },
  remote: { category: 'appliance', ja: 'リモコン', sub: '家電' },
  keyboard: { category: 'computer', ja: 'キーボード', sub: 'PC周辺機器' },
  'cell phone': { category: 'phone', ja: 'スマートフォン', sub: 'モバイル' },
  microwave: { category: 'appliance', ja: '電子レンジ', sub: '家電' },
  oven: { category: 'appliance', ja: 'オーブン', sub: '家電' },
  toaster: { category: 'appliance', ja: 'トースター', sub: '家電' },
  refrigerator: { category: 'appliance', ja: '冷蔵庫', sub: '家電' },
  book: { category: 'text', ja: '本', sub: '書籍' },
  clock: { category: 'product', ja: '時計', sub: '商品' },
  vase: { category: 'product', ja: '花瓶', sub: '商品' },
  scissors: { category: 'product', ja: 'はさみ', sub: '商品' },
  'teddy bear': { category: 'product', ja: 'ぬいぐるみ', sub: '商品' },
  'hair drier': { category: 'cosmetics', ja: 'ドライヤー', sub: '美容家電' },
  toothbrush: { category: 'cosmetics', ja: '歯ブラシ', sub: '日用品' },
};

export function mapLabel(label: string): { category: ObjectCategory; ja: string; sub: string } {
  return COCO_MAP[label] ?? { category: 'other', ja: label, sub: '物体' };
}
